var subject = 'nationalcapitals';
subjects[subject] = {
name:'National Capitals',
reversible:true,
language:false,
sketch:false,
translit:false,
audio:false,
db: false,
cards: [
{q:'China', a:'Beijing'},
{q:'India', a:'New Delhi'},
{q:'United States', a:'Washington, D.C.'},
{q:'Indonesia', a:'Jakarta'},
{q:'Brazil', a:'Brasília'},
{q:'Pakistan', a:'Islamabad'},
{q:'Nigeria', a:'Abuja'},
{q:'Bangladesh', a:'Dhaka'},
{q:'Russia', a:'Moscow'},
{q:'Japan', a:'Tokyo'},
{q:'Mexico', a:'Mexico City'},
{q:'Philippines', a:'Manila'},
{q:'Vietnam', a:'Hanoi'},
{q:'Ethiopia', a:'Addis Ababa'},
{q:'Egypt', a:'Cairo'},
{q:'Germany', a:'Berlin'},
{q:'Iran', a:'Tehran'},
{q:'Congo', a:'Kinshasa'},
{q:'Turkey', a:'Ankara'},
{q:'France', a:'Paris'},
{q:'Thailand', a:'Bangkok'},
{q:'United Kingdom', a:'London'},
{q:'Italy', a:'Rome'},
{q:'South Africa', a:'Pretoria'},
{q:'Myanmar (Burma)', a:'Naypyidaw'},
{q:'Tanzania', a:'Dodoma'},
{q:'South Korea', a:'Seoul'},
{q:'Colombia', a:'Bogotá'},
{q:'Spain', a:'Madrid'},
{q:'Kenya', a:'Nairobi'},
{q:'Argentina', a:'Buenos Aires'},
{q:'Ukraine', a:'Kiev'},
{q:'Algeria', a:'Algiers'},
{q:'Poland', a:'Warsaw'},
{q:'Sudan', a:'Khartoum'},
{q:'Iraq', a:'Baghdad'},
{q:'Canada', a:'Ottawa'},
{q:'Uganda', a:'Kampala'},
{q:'Morocco', a:'Rabat'},
{q:'Afghanistan', a:'Kabul'},
{q:'Saudi Arabia', a:'Riyadh'},
{q:'Peru', a:'Lima'},
{q:'Uzbekistan', a:'Tashkent'},
{q:'Malaysia', a:'Kuala Lumpur'},
{q:'Venezuela', a:'Caracas'},
{q:'Nepal', a:'Kathmandu'},
{q:'Ghana', a:'Accra'},
{q:'Yemen', a:"Sana'a"},
{q:'Mozambique', a:'Maputo'},
{q:'North Korea', a:'Pyongyang'},
{q:'Angola', a:'Luanda'},
{q:'Australia', a:'Canberra'},
{q:'Taiwan', a:'Taipei'},
{q:'Cameroon', a:'Yaoundé'},
{q:'Syria', a:'Damascus'},
{q:"Côte d'Ivoire (Ivory Coast)", a:'Yamoussoukro'},
{q:'Madagascar', a:'Antananarivo'},
{q:'Sri Lanka', a:'Sri Jayawardenepura-Kotte'},
{q:'Romania', a:'Bucharest'},
{q:'Niger', a:'Niamey'},
{q:'Burkina Faso', a:'Ouagadougou'},
{q:'Chile', a:'Santiago'},
{q:'Mali', a:'Bamako'},
{q:'Kazakhstan', a:'Astana'},
{q:'Netherlands', a:'Amsterdam'},
{q:'Malawi', a:'Lilongwe'},
{q:'Guatemala', a:'Guatemala City'},
{q:'Ecuador', a:'Quito'},
{q:'Zambia', a:'Lusaka'},
{q:'Cambodia', a:'Phnom Penh'},
{q:'Chad', a:"N'Djamena"},
{q:'Senegal', a:'Dakar'},
{q:'Zimbabwe', a:'Harare'},
{q:'South Sudan', a:'Juba'},
{q:'Bolivia', a:'Sucre'},
{q:'Belgium', a:'Brussels'},
{q:'Cuba', a:'Havana'},
{q:'Rwanda', a:'Kigali'},
{q:'Tunisia', a:'Tunis'},
{q:'Haiti', a:'Port-au-Prince'},
{q:'Greece', a:'Athens'},
{q:'Somalia', a:'Mogadishu'},
{q:'Guinea', a:'Conakry'},
{q:'Czech Republic', a:'Prague'},
{q:'Dominican Republic', a:'Santo Domingo'},
{q:'Portugal', a:'Lisbon'},
{q:'Benin', a:'Porto-Novo'},
{q:'Hungary', a:'Budapest'},
{q:'Burundi', a:'Bujumbura'},
{q:'Sweden', a:'Stockholm'},
{q:'Azerbaijan', a:'Baku'},
{q:'Belarus', a:'Minsk'},
{q:'United Arab Emirates', a:'Abu Dhabi'},
{q:'Honduras', a:'Tegucigalpa'},
{q:'Austria', a:'Vienna'},
{q:'Israel', a:'Jerusalem'},
{q:'Tajikistan', a:'Dushanbe'},
{q:'Switzerland', a:'Bern'},
{q:'Papua New Guinea', a:'Port Moresby'},
{q:'Togo', a:'Lomé'},
{q:'Hong Kong', a:'Victoria'},
{q:'Bulgaria', a:'Sofia'},
{q:'Serbia', a:'Belgrade'},
{q:'Paraguay', a:'Asunción'},
{q:'Laos', a:'Vientiane'},
{q:'Jordan', a:'Amman'},
{q:'Sierra Leone', a:'Freetown'},
{q:'El Salvador', a:'San Salvador'},
{q:'Libya', a:'Tripoli'},
{q:'Nicaragua', a:'Managua'},
{q:'Kyrgyzstan', a:'Bishkek'},
{q:'Denmark', a:'Copenhagen'},
{q:'Finland', a:'Helsinki'},
{q:'Singapore', a:'Singapore'},
{q:'Slovakia', a:'Bratislava'},
{q:'Eritrea', a:'Asmara'},
{q:'Norway', a:'Oslo'},
{q:'Central African Republic', a:'Bangui'},
{q:'Costa Rica', a:'San José'},
{q:'Turkmenistan', a:'Ashgabat'},
{q:'Palestine', a:'Ramallah'},
{q:'Congo (Congo-Brazzaville)', a:'Brazzaville'},
{q:'Ireland', a:'Dublin'},
{q:'New Zealand', a:'Wellington'},
{q:'Liberia', a:'Monrovia'},
{q:'Croatia', a:'Zagreb'},
{q:'Oman', a:'Muscat'},
{q:'Lebanon', a:'Beirut'},
{q:'Bosnia and Herzegovina', a:'Sarajevo'},
{q:'Georgia [Europe]', a:'Tbilisi'},
{q:'Mauritania', a:'Nouakchott'},
{q:'Moldova', a:'Chişinău'},
{q:'Puerto Rico', a:'San Juan'},
{q:'Somaliland', a:'Hargeisa'},
{q:'Uruguay', a:'Montevideo'},
{q:'Kuwait', a:'Kuwait City'},
{q:'Mongolia', a:'Ulaanbaatar'},
{q:'Armenia', a:'Yerevan'},
{q:'Lithuania', a:'Vilnius'},
{q:'Albania', a:'Tirana'},
{q:'Jamaica', a:'Kingston'},
{q:'Namibia', a:'Windhoek'},
{q:'Botswana', a:'Gaborone'},
{q:'Lesotho', a:'Maseru'},
{q:'Qatar', a:'Doha'},
{q:'Slovenia', a:'Ljubljana'},
{q:'Macedonia', a:'Skopje'},
{q:'Latvia', a:'Riga'},
{q:'Gambia', a:'Banjul'},
{q:'Guinea-Bissau', a:'Bissau'},
{q:'Kosovo', a:'Pristina'},
{q:'Gabon', a:'Libreville'},
{q:'Equatorial Guinea', a:'Malabo'},
{q:'Bahrain', a:'Manama'},
{q:'Trinidad and Tobago', a:'Port of Spain'},
{q:'Estonia', a:'Tallinn'},
{q:'Mauritius', a:'Port Louis'},
{q:'East Timor (Timor-Leste)', a:'Dili'},
{q:'Swaziland', a:'Mbabane'},
{q:'Djibouti', a:'Djibouti'},
{q:'Fiji', a:'Suva'},
{q:'Cyprus [Europe]', a:'Nicosia'},
{q:'Réunion', a:'Saint-Denis'},
{q:'Comoros', a:'Moroni'},
{q:'Bhutan', a:'Thimphu'},
{q:'Guyana', a:'Georgetown'},
{q:'Macau', a:'Macau'},
{q:'Montenegro', a:'Podgorica'},
{q:'Solomon Islands', a:'Honiara'},
{q:'Luxembourg', a:'Luxembourg'},
{q:'Suriname', a:'Paramaribo'},
{q:'Cape Verde', a:'Praia'},
{q:'Transnistria', a:'Tiraspol'},
{q:'Malta', a:'Valletta'},
{q:'Guadeloupe', a:'Basse-Terre'},
{q:'Brunei', a:'Bandar Seri Begawan'},
{q:'Martinique', a:'Fort-de-France'},
{q:'Bahamas', a:'Nassau'},
{q:'Belize', a:'Belmopan'},
{q:'Maldives', a:'Malé'},
{q:'Iceland', a:'Reykjavík'},
{q:'Barbados', a:'Bridgetown'},
{q:'New Caledonia', a:'Nouméa'},
{q:'French Polynesia', a:'Papeete'},
{q:'Vanuatu', a:'Port Vila'},
{q:'French Guiana', a:'Cayenne'},
{q:'Mayotte', a:'Mamoudzou'},
{q:'Samoa', a:'Apia'},
{q:'Sao Tome and Principe', a:'São Tomé'},
{q:'Saint Lucia', a:'Castries'},
{q:'Guam', a:'Hagåtña'},
{q:'Saint Vincent and the Grenadines', a:'Kingstown'},
{q:'Aruba', a:'Oranjestad'},
{q:'Kiribati', a:'Tarawa'},
{q:'United States Virgin Islands', a:'Charlotte Amalie'},
{q:'Grenada', a:"St. George's"},
{q:'Tonga', a:'Nukuʻalofa'},
{q:'Jersey', a:'Saint Helier'},
{q:'Seychelles', a:'Victoria'},
{q:'Antigua and Barbuda', a:"St. John's"},
{q:'Isle of Man', a:'Douglas,British Crown dependency'},
{q:'Andorra', a:'Andorra la Vella'},
{q:'Dominica', a:'Roseau'},
{q:'Guernsey', a:'Saint Peter Port'},
{q:'Bermuda', a:'Hamilton'},
{q:'Marshall Islands', a:'Majuro'},
{q:'Saint Kitts and Nevis', a:'Basseterre'},
{q:'Greenland', a:'Nuuk'},
{q:'Cayman Islands', a:'George Town'},
{q:'American Samoa', a:'Pago Pago'},
{q:'Northern Mariana Islands', a:'Saipan'},
{q:'Faroe Islands', a:'Tórshavn'},
{q:'Monaco', a:'Monaco'},
{q:'Liechtenstein', a:'Vaduz'},
{q:'San Marino', a:'San Marino'},
{q:'Turks and Caicos Islands', a:'Cockburn Town'},
{q:'Gibraltar', a:'Gibraltar'},
{q:'Åland Islands', a:'Mariehamn'},
{q:'British Virgin Islands', a:'Road Town'},
{q:'Palau', a:'Ngerulmud'},
{q:'Bonaire', a:'Kralendijk'},
{q:'Cook Islands', a:'Avarua'},
{q:'Anguilla', a:'The Valley'},
{q:'Wallis and Futuna', a:'Mata-Utu'},
{q:'Tuvalu', a:'Funafuti'},
{q:'Nauru', a:'Yaren'},
]
}
onscriptloaded(subject);
